#!/bin/ash

###special varabkes in shell scripting
echo "The name of the script is: $0"
echo "The first argument is: $1"
echo "The second argument is: $2"                           
echo "The total number of arguments is: $#"
echo "All the arguments are: $*"
echo "The process ID of the current script is: $$"
echo "The exit status of the last command is: $?"
echo "The last background process ID is: $!"
echo "The username of the current user is: $USER"
echo "The home directory of the current user is: $HOME"
echo "The current working directory is: $PWD"
echo "The shell being used is: $SHELL"
echo "The operating system name is: $OSTYPE"
echo "The current date and time is: $(date)"
echo "The current version of bash is: $BASH_VERSION"
echo "The number of CPU cores is: $(nproc)"
echo "The total memory available is: $(free -h | grep Mem | awk '{print $2}')"  
echo "The system uptime is: $(uptime -p)"
echo "The current logged in users are: $(who)"
echo "The current network configuration is: $(ifconfig | head -n 5)"
echo "The disk usage of the root directory is: $(df -h / | tail -1)"
echo "The current environment variables are: $(printenv | head -n 5)"
echo "The current shell options are: $(shopt)"
echo "The current locale settings are: $(locale | head -n 5)"
echo "The current date in YYYY-MM-DD format is: $(date +%F)"
echo "The current time in HH:MM:SS format is: $(date +%T)"
echo "The current user's group is: $(id -gn)"
echo "The current user's groups are: $(id -Gn)"
echo "The current user's home directory is: $(eval echo ~$USER)"
echo "The current user's shell is: $(getent passwd $USER | cut -d: -f7)"
